type Query {
  post(id: ID!): Post!
  user(id: ID!): User!

  node(id: ID!): Node!

  posts: [Post!]
  users: [User!]
}

interface Node {
  id: ID!
}

union User = UserWeb | UserAdmin

type Post implements Node {
  id: ID!
  title: String!
  author: User!
}

type UserWeb implements Node {
  id: ID!
  type: String!
  name: String!
  posts: [Post!]
}

type UserAdmin implements Node {
  id: ID!
  type: String!
  name: String!
}
